### ISSUE TITLE
Doesn't work in block-level HTML tags in markdown

### ISSUE THREAD

**Issue by sharmaeklavya2** [martenlienen/pelican-katex#16]
I'm using `pelican-katex` for my blog, where I write articles in markdown. But the `$` delimiters don't work inside `<figcaption>` tags, which are nested inside `<figure>` tags.

I guess that's because (part of) `pelican-katex` is a [`python-markdown extension`](https://python-markdown.github.io/extensions/), and `python-markdown` says it's supposed to follow John Gruber's markdown spec, and that spec says that text inside block-level HTML tags is not processed. `<figure>` is a block-level tag.

**Comment by martenlienen** [comment]
I have checked the source of `python-markdown` and I think there is no viable, generally applicable solution here because the HTML content of block level elements is explicitly restored in a postprocessing step. However, for your one case, maybe you can add something like the following to your `pelicanconf.py`:
```python
import markdown.util

for el in ["figure", "figcaption"]:
    markdown.util.BLOCK_LEVEL_ELEMENTS.remove(el)
```

**Comment by sharmaeklavya2** [comment]
Thanks for the quick response and suggesting the workaround.
